### ISSUE TITLE
OSError: [Errno 88] Socket operation on non-socket

### ISSUE THREAD

**Issue by Scottie313** [Kozea/flipflop#1]
Hello!
When I tried to use your module I received following error message:

```
# /usr/bin/python3.3 helloapp.fcgi
Traceback (most recent call last):
  File "helloapp.fcgi", line 7, in <module>
    WSGIServer(app).run()
  File "/usr/lib/python3.3/site-packages/flipflop-1.0-py3.3.egg/flipflop.py", line 938, in run
OSError: [Errno 88] Socket operation on non-socket
```

Where my file `helloapp.fcgi` is:

```
#!/usr/bin/python3.3

from flipflop import WSGIServer
from helloflask import app

if __name__ == '__main__':
    WSGIServer(app).run()
```

I'm using Python 3.3.4 version on the CentOS 32-bit machine.

**Comment by ealvarez1203** [comment]
Hi how do you run the script from the Apache?

**Comment by currupipi** [comment]
Hi have the same issue

My python version:
# /usr/bin/env python -V
Python 2.7.3

My apache2 config vhost includes one page being served by rack and the cgi as a callback url running a fcgi

<VirtualHost *:80>
    ServerName XXXXXX
    DocumentRoot /var/www/XXXXX

    ScriptAlias /cgi-bin/ /usr/lib/cgi-bin/
        <Directory "/usr/lib/cgi-bin">
            AllowOverride None
            Options +ExecCGI -MultiViews +SymLinksIfOwnerMatch
            AddHandler cgi-script .cgi
            AddHandler fastcgi-script .fcgi .fcg .fpl
            Order allow,deny
            Allow from all
        </Directory>

    ErrorLog /var/log/apache2/XXXX
    CustomLog /var/log/apache2/XXXXX

    RackAutoDetect On
    Alias /static /usr/local/lib/python2.7/dist-packages/XXXX/XXXX
</VirtualHost>

The error I get is that (just forcing the fcgi without any payload):

# ./python.fcgi
Traceback (most recent call last):
  File "./python.fcgi", line 60, in <module>
    WSGIServer(app).run()
  File "/usr/local/lib/python2.7/dist-packages/flipflop.py", line 938, in run
    sock.getpeername()
socket.error: [Errno 88] Socket operation on non-socket

Any help will be more than welcome, thanks!

**Comment by liZe** [comment]
Launching `python.fcgi` directly won't work. You have to get the real logs from Apache if you want some help :smile:.
